//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceSP {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        private System.Nullable<decimal> GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        private System.Nullable<System.DateTime> NgayCapNhatField;
        
        private System.Nullable<int> SoLuongField;
        
        private System.Nullable<int> MaNSXField;
        
        private System.Nullable<int> MaLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> NgayCapNhat {
            get {
                return this.NgayCapNhatField;
            }
            set {
                if ((this.NgayCapNhatField.Equals(value) != true)) {
                    this.NgayCapNhatField = value;
                    this.RaisePropertyChanged("NgayCapNhat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> MaNSX {
            get {
                return this.MaNSXField;
            }
            set {
                if ((this.MaNSXField.Equals(value) != true)) {
                    this.MaNSXField = value;
                    this.RaisePropertyChanged("MaNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSP.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplication1.ServiceSP.HelloWorldResponse HelloWorld(WindowsFormsApplication1.ServiceSP.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.HelloWorldResponse> HelloWorldAsync(WindowsFormsApplication1.ServiceSP.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSP", ReplyAction="*")]
        WindowsFormsApplication1.ServiceSP.GetAllSPResponse GetAllSP(WindowsFormsApplication1.ServiceSP.GetAllSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSP", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetAllSPResponse> GetAllSPAsync(WindowsFormsApplication1.ServiceSP.GetAllSPRequest request);
        
        // CODEGEN: Generating message contract since element name GetSanPhamIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSanPhamID", ReplyAction="*")]
        WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse GetSanPhamID(WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSanPhamID", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse> GetSanPhamIDAsync(WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest request);
        
        // CODEGEN: Generating message contract since element name TenSP from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSP", ReplyAction="*")]
        WindowsFormsApplication1.ServiceSP.AddSPResponse AddSP(WindowsFormsApplication1.ServiceSP.AddSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSP", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.AddSPResponse> AddSPAsync(WindowsFormsApplication1.ServiceSP.AddSPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplication1.ServiceSP.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplication1.ServiceSP.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSP", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.GetAllSPRequestBody Body;
        
        public GetAllSPRequest() {
        }
        
        public GetAllSPRequest(WindowsFormsApplication1.ServiceSP.GetAllSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSPRequestBody {
        
        public GetAllSPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.GetAllSPResponseBody Body;
        
        public GetAllSPResponse() {
        }
        
        public GetAllSPResponse(WindowsFormsApplication1.ServiceSP.GetAllSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceSP.SanPham[] GetAllSPResult;
        
        public GetAllSPResponseBody() {
        }
        
        public GetAllSPResponseBody(WindowsFormsApplication1.ServiceSP.SanPham[] GetAllSPResult) {
            this.GetAllSPResult = GetAllSPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSanPhamIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSanPhamID", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequestBody Body;
        
        public GetSanPhamIDRequest() {
        }
        
        public GetSanPhamIDRequest(WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSanPhamIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetSanPhamIDRequestBody() {
        }
        
        public GetSanPhamIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSanPhamIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSanPhamIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponseBody Body;
        
        public GetSanPhamIDResponse() {
        }
        
        public GetSanPhamIDResponse(WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSanPhamIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceSP.SanPham[] GetSanPhamIDResult;
        
        public GetSanPhamIDResponseBody() {
        }
        
        public GetSanPhamIDResponseBody(WindowsFormsApplication1.ServiceSP.SanPham[] GetSanPhamIDResult) {
            this.GetSanPhamIDResult = GetSanPhamIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSP", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.AddSPRequestBody Body;
        
        public AddSPRequest() {
        }
        
        public AddSPRequest(WindowsFormsApplication1.ServiceSP.AddSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TenSP;
        
        public AddSPRequestBody() {
        }
        
        public AddSPRequestBody(string TenSP) {
            this.TenSP = TenSP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceSP.AddSPResponseBody Body;
        
        public AddSPResponse() {
        }
        
        public AddSPResponse(WindowsFormsApplication1.ServiceSP.AddSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSPResult;
        
        public AddSPResponseBody() {
        }
        
        public AddSPResponseBody(bool AddSPResult) {
            this.AddSPResult = AddSPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApplication1.ServiceSP.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceSP.WebServiceSoap>, WindowsFormsApplication1.ServiceSP.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceSP.HelloWorldResponse WindowsFormsApplication1.ServiceSP.WebServiceSoap.HelloWorld(WindowsFormsApplication1.ServiceSP.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplication1.ServiceSP.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceSP.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.HelloWorldRequestBody();
            WindowsFormsApplication1.ServiceSP.HelloWorldResponse retVal = ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.HelloWorldResponse> WindowsFormsApplication1.ServiceSP.WebServiceSoap.HelloWorldAsync(WindowsFormsApplication1.ServiceSP.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApplication1.ServiceSP.HelloWorldRequest inValue = new WindowsFormsApplication1.ServiceSP.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.HelloWorldRequestBody();
            return ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceSP.GetAllSPResponse WindowsFormsApplication1.ServiceSP.WebServiceSoap.GetAllSP(WindowsFormsApplication1.ServiceSP.GetAllSPRequest request) {
            return base.Channel.GetAllSP(request);
        }
        
        public WindowsFormsApplication1.ServiceSP.SanPham[] GetAllSP() {
            WindowsFormsApplication1.ServiceSP.GetAllSPRequest inValue = new WindowsFormsApplication1.ServiceSP.GetAllSPRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.GetAllSPRequestBody();
            WindowsFormsApplication1.ServiceSP.GetAllSPResponse retVal = ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).GetAllSP(inValue);
            return retVal.Body.GetAllSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetAllSPResponse> WindowsFormsApplication1.ServiceSP.WebServiceSoap.GetAllSPAsync(WindowsFormsApplication1.ServiceSP.GetAllSPRequest request) {
            return base.Channel.GetAllSPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetAllSPResponse> GetAllSPAsync() {
            WindowsFormsApplication1.ServiceSP.GetAllSPRequest inValue = new WindowsFormsApplication1.ServiceSP.GetAllSPRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.GetAllSPRequestBody();
            return ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).GetAllSPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse WindowsFormsApplication1.ServiceSP.WebServiceSoap.GetSanPhamID(WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest request) {
            return base.Channel.GetSanPhamID(request);
        }
        
        public WindowsFormsApplication1.ServiceSP.SanPham[] GetSanPhamID(int id) {
            WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest inValue = new WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequestBody();
            inValue.Body.id = id;
            WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse retVal = ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).GetSanPhamID(inValue);
            return retVal.Body.GetSanPhamIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse> WindowsFormsApplication1.ServiceSP.WebServiceSoap.GetSanPhamIDAsync(WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest request) {
            return base.Channel.GetSanPhamIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.GetSanPhamIDResponse> GetSanPhamIDAsync(int id) {
            WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest inValue = new WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.GetSanPhamIDRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).GetSanPhamIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceSP.AddSPResponse WindowsFormsApplication1.ServiceSP.WebServiceSoap.AddSP(WindowsFormsApplication1.ServiceSP.AddSPRequest request) {
            return base.Channel.AddSP(request);
        }
        
        public bool AddSP(string TenSP) {
            WindowsFormsApplication1.ServiceSP.AddSPRequest inValue = new WindowsFormsApplication1.ServiceSP.AddSPRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.AddSPRequestBody();
            inValue.Body.TenSP = TenSP;
            WindowsFormsApplication1.ServiceSP.AddSPResponse retVal = ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).AddSP(inValue);
            return retVal.Body.AddSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.AddSPResponse> WindowsFormsApplication1.ServiceSP.WebServiceSoap.AddSPAsync(WindowsFormsApplication1.ServiceSP.AddSPRequest request) {
            return base.Channel.AddSPAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceSP.AddSPResponse> AddSPAsync(string TenSP) {
            WindowsFormsApplication1.ServiceSP.AddSPRequest inValue = new WindowsFormsApplication1.ServiceSP.AddSPRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceSP.AddSPRequestBody();
            inValue.Body.TenSP = TenSP;
            return ((WindowsFormsApplication1.ServiceSP.WebServiceSoap)(this)).AddSPAsync(inValue);
        }
    }
}
