//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        private System.Nullable<decimal> GiaBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HinhAnhField;
        
        private System.Nullable<System.DateTime> NgayCapNhatField;
        
        private System.Nullable<int> SoLuongField;
        
        private System.Nullable<int> MaNSXField;
        
        private System.Nullable<int> MaLoaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> GiaBan {
            get {
                return this.GiaBanField;
            }
            set {
                if ((this.GiaBanField.Equals(value) != true)) {
                    this.GiaBanField = value;
                    this.RaisePropertyChanged("GiaBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HinhAnh {
            get {
                return this.HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this.HinhAnhField, value) != true)) {
                    this.HinhAnhField = value;
                    this.RaisePropertyChanged("HinhAnh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> NgayCapNhat {
            get {
                return this.NgayCapNhatField;
            }
            set {
                if ((this.NgayCapNhatField.Equals(value) != true)) {
                    this.NgayCapNhatField = value;
                    this.RaisePropertyChanged("NgayCapNhat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> MaNSX {
            get {
                return this.MaNSXField;
            }
            set {
                if ((this.MaNSXField.Equals(value) != true)) {
                    this.MaNSXField = value;
                    this.RaisePropertyChanged("MaNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> MaLoai {
            get {
                return this.MaLoaiField;
            }
            set {
                if ((this.MaLoaiField.Equals(value) != true)) {
                    this.MaLoaiField = value;
                    this.RaisePropertyChanged("MaLoai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Web1.ServiceReference1.HelloWorldResponse HelloWorld(Web1.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Web1.ServiceReference1.HelloWorldResponse> HelloWorldAsync(Web1.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllSPResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSP", ReplyAction="*")]
        Web1.ServiceReference1.GetAllSPResponse GetAllSP(Web1.ServiceReference1.GetAllSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSP", ReplyAction="*")]
        System.Threading.Tasks.Task<Web1.ServiceReference1.GetAllSPResponse> GetAllSPAsync(Web1.ServiceReference1.GetAllSPRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        Web1.ServiceReference1.GetProductResponse GetProduct(Web1.ServiceReference1.GetProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<Web1.ServiceReference1.GetProductResponse> GetProductAsync(Web1.ServiceReference1.GetProductRequest request);
        
        // CODEGEN: Generating message contract since element name sp from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSP", ReplyAction="*")]
        Web1.ServiceReference1.AddSPResponse AddSP(Web1.ServiceReference1.AddSPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSP", ReplyAction="*")]
        System.Threading.Tasks.Task<Web1.ServiceReference1.AddSPResponse> AddSPAsync(Web1.ServiceReference1.AddSPRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Web1.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Web1.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSP", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.GetAllSPRequestBody Body;
        
        public GetAllSPRequest() {
        }
        
        public GetAllSPRequest(Web1.ServiceReference1.GetAllSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllSPRequestBody {
        
        public GetAllSPRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.GetAllSPResponseBody Body;
        
        public GetAllSPResponse() {
        }
        
        public GetAllSPResponse(Web1.ServiceReference1.GetAllSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web1.ServiceReference1.SanPham[] GetAllSPResult;
        
        public GetAllSPResponseBody() {
        }
        
        public GetAllSPResponseBody(Web1.ServiceReference1.SanPham[] GetAllSPResult) {
            this.GetAllSPResult = GetAllSPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.GetProductRequestBody Body;
        
        public GetProductRequest() {
        }
        
        public GetProductRequest(Web1.ServiceReference1.GetProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetProductRequestBody() {
        }
        
        public GetProductRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.GetProductResponseBody Body;
        
        public GetProductResponse() {
        }
        
        public GetProductResponse(Web1.ServiceReference1.GetProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web1.ServiceReference1.SanPham GetProductResult;
        
        public GetProductResponseBody() {
        }
        
        public GetProductResponseBody(Web1.ServiceReference1.SanPham GetProductResult) {
            this.GetProductResult = GetProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSP", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.AddSPRequestBody Body;
        
        public AddSPRequest() {
        }
        
        public AddSPRequest(Web1.ServiceReference1.AddSPRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSPRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Web1.ServiceReference1.SanPham sp;
        
        public AddSPRequestBody() {
        }
        
        public AddSPRequestBody(Web1.ServiceReference1.SanPham sp) {
            this.sp = sp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSPResponse", Namespace="http://tempuri.org/", Order=0)]
        public Web1.ServiceReference1.AddSPResponseBody Body;
        
        public AddSPResponse() {
        }
        
        public AddSPResponse(Web1.ServiceReference1.AddSPResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSPResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSPResult;
        
        public AddSPResponseBody() {
        }
        
        public AddSPResponseBody(bool AddSPResult) {
            this.AddSPResult = AddSPResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Web1.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Web1.ServiceReference1.WebServiceSoap>, Web1.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web1.ServiceReference1.HelloWorldResponse Web1.ServiceReference1.WebServiceSoap.HelloWorld(Web1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Web1.ServiceReference1.HelloWorldRequest inValue = new Web1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Web1.ServiceReference1.HelloWorldRequestBody();
            Web1.ServiceReference1.HelloWorldResponse retVal = ((Web1.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web1.ServiceReference1.HelloWorldResponse> Web1.ServiceReference1.WebServiceSoap.HelloWorldAsync(Web1.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web1.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            Web1.ServiceReference1.HelloWorldRequest inValue = new Web1.ServiceReference1.HelloWorldRequest();
            inValue.Body = new Web1.ServiceReference1.HelloWorldRequestBody();
            return ((Web1.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web1.ServiceReference1.GetAllSPResponse Web1.ServiceReference1.WebServiceSoap.GetAllSP(Web1.ServiceReference1.GetAllSPRequest request) {
            return base.Channel.GetAllSP(request);
        }
        
        public Web1.ServiceReference1.SanPham[] GetAllSP() {
            Web1.ServiceReference1.GetAllSPRequest inValue = new Web1.ServiceReference1.GetAllSPRequest();
            inValue.Body = new Web1.ServiceReference1.GetAllSPRequestBody();
            Web1.ServiceReference1.GetAllSPResponse retVal = ((Web1.ServiceReference1.WebServiceSoap)(this)).GetAllSP(inValue);
            return retVal.Body.GetAllSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web1.ServiceReference1.GetAllSPResponse> Web1.ServiceReference1.WebServiceSoap.GetAllSPAsync(Web1.ServiceReference1.GetAllSPRequest request) {
            return base.Channel.GetAllSPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web1.ServiceReference1.GetAllSPResponse> GetAllSPAsync() {
            Web1.ServiceReference1.GetAllSPRequest inValue = new Web1.ServiceReference1.GetAllSPRequest();
            inValue.Body = new Web1.ServiceReference1.GetAllSPRequestBody();
            return ((Web1.ServiceReference1.WebServiceSoap)(this)).GetAllSPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web1.ServiceReference1.GetProductResponse Web1.ServiceReference1.WebServiceSoap.GetProduct(Web1.ServiceReference1.GetProductRequest request) {
            return base.Channel.GetProduct(request);
        }
        
        public Web1.ServiceReference1.SanPham GetProduct(int id) {
            Web1.ServiceReference1.GetProductRequest inValue = new Web1.ServiceReference1.GetProductRequest();
            inValue.Body = new Web1.ServiceReference1.GetProductRequestBody();
            inValue.Body.id = id;
            Web1.ServiceReference1.GetProductResponse retVal = ((Web1.ServiceReference1.WebServiceSoap)(this)).GetProduct(inValue);
            return retVal.Body.GetProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web1.ServiceReference1.GetProductResponse> Web1.ServiceReference1.WebServiceSoap.GetProductAsync(Web1.ServiceReference1.GetProductRequest request) {
            return base.Channel.GetProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web1.ServiceReference1.GetProductResponse> GetProductAsync(int id) {
            Web1.ServiceReference1.GetProductRequest inValue = new Web1.ServiceReference1.GetProductRequest();
            inValue.Body = new Web1.ServiceReference1.GetProductRequestBody();
            inValue.Body.id = id;
            return ((Web1.ServiceReference1.WebServiceSoap)(this)).GetProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Web1.ServiceReference1.AddSPResponse Web1.ServiceReference1.WebServiceSoap.AddSP(Web1.ServiceReference1.AddSPRequest request) {
            return base.Channel.AddSP(request);
        }
        
        public bool AddSP(Web1.ServiceReference1.SanPham sp) {
            Web1.ServiceReference1.AddSPRequest inValue = new Web1.ServiceReference1.AddSPRequest();
            inValue.Body = new Web1.ServiceReference1.AddSPRequestBody();
            inValue.Body.sp = sp;
            Web1.ServiceReference1.AddSPResponse retVal = ((Web1.ServiceReference1.WebServiceSoap)(this)).AddSP(inValue);
            return retVal.Body.AddSPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Web1.ServiceReference1.AddSPResponse> Web1.ServiceReference1.WebServiceSoap.AddSPAsync(Web1.ServiceReference1.AddSPRequest request) {
            return base.Channel.AddSPAsync(request);
        }
        
        public System.Threading.Tasks.Task<Web1.ServiceReference1.AddSPResponse> AddSPAsync(Web1.ServiceReference1.SanPham sp) {
            Web1.ServiceReference1.AddSPRequest inValue = new Web1.ServiceReference1.AddSPRequest();
            inValue.Body = new Web1.ServiceReference1.AddSPRequestBody();
            inValue.Body.sp = sp;
            return ((Web1.ServiceReference1.WebServiceSoap)(this)).AddSPAsync(inValue);
        }
    }
}
